import test from 'node:test';import assert from 'node:assert/strict';
import {extractLeaders,selectFilings,links,publicationDate} from '../discovery.js';
import {collectResearch} from '../collector.js';import {buildBrief} from '../research.js';import {JobQueue} from '../jobs.js';import {parseAccounts} from '../public/accounts.js';import {validateGraph} from '../public/org.js';
const leadership='<main><article><h2>Jane Smith</h2><p>Chief Technology Officer</p><a href="/leadership/jane">Biography</a></article><article><h2>David Jones</h2><p>Chief Information Security Officer</p></article></main>';
test('leadership cards produce named people with citations but no reporting hierarchy',()=>{const people=extractLeaders(leadership,'https://acme.example/leadership','S1',null);assert.equal(people.length,2);assert.equal(people[0].name,'Jane Smith');assert.match(people[0].title,/Chief Technology Officer/);assert.equal(people[0].profileUrl,'https://acme.example/leadership/jane');assert.equal(people[0].reportsTo,null);assert.equal(people[0].sourceId,'S1');});
test('filing selection includes all eligible 10-K and 10-Q filings and amendments, newest first',()=>{const r={form:['10-Q','10-K','8-K','10-Q/A','10-K'],filingDate:['2025-05-01','2025-02-01','2025-03-01','2025-05-20','2022-02-01'],accessionNumber:['a','b','c','d','e'],primaryDocument:['a.htm','b.htm','c.htm','d.htm','e.htm']};const out=selectFilings(r,{months:24,now:Date.parse('2025-06-01'),max:2});assert.equal(out.total,3);assert.equal(out.selected.length,2);assert.ok(out.selected[0].amendment);assert.equal(out.selected[1].date,'2025-05-01');});
test('source dates do not use retrieval dates',()=>{assert.equal(publicationDate('<time datetime="2025-04-20">April</time>'),'2025-04-20');assert.equal(publicationDate('<p>Copyright 2026</p>'),null);const found=links('<a href="/deck.pdf">Investor Day March 15, 2025</a>','https://acme.example/ir');assert.equal(found[0].date,'2025-03-15');assert.equal(found[0].type,'Investor day');});
test('CSV supports quoted company names, optional official pages and deduplication',()=>{const rows=parseAccounts('company,ticker,investor_url\n"Acme, Inc.",,https://acme.example/ir\nMicrosoft,MSFT,https://microsoft.com/investor\nMicrosoft,MSFT,');assert.equal(rows.length,2);assert.equal(rows[0].company,'Acme, Inc.');assert.equal(rows[1].company,'MSFT');assert.throws(()=>parseAccounts('"missing quote'),/unclosed/);assert.throws(()=>parseAccounts('company\n'),/between/);});
test('org graph rejects cycles, nonexistent parents and unsafe links',()=>{const nodes=[{id:'a',name:'Jane',x:10,y:10,reportsTo:'b'},{id:'b',name:'David',x:100,y:10,reportsTo:'a'}];assert.throws(()=>validateGraph({nodes}),/cycle/);nodes[1].reportsTo=null;assert.doesNotThrow(()=>validateGraph({nodes}));nodes[0].reportsTo='missing';assert.throws(()=>validateGraph({nodes}),/missing/);nodes[0].reportsTo=null;nodes[0].sourceUrl='javascript:alert(1)';assert.throws(()=>validateGraph({nodes}),/HTTPS/);});
const tickers={0:{ticker:'ACME',title:'ACME INC',cik_str:1}};
const issuer={name:'ACME INC',filings:{files:[],recent:{form:['10-Q','10-K'],filingDate:['2025-05-01','2025-02-01'],reportDate:['2025-03-31','2024-12-31'],accessionNumber:['001-001','001-002'],primaryDocument:['q.htm','k.htm']}}};
function fixture(){const pages={
 'https://acme.example/ir':'<main><h1>Investor center</h1><a href="/annual-reports">Annual Reports</a><a href="/events">Events</a><a href="/leadership">Leadership</a></main>',
 'https://acme.example/annual-reports':'<main><h1>Annual reports</h1><a href="/report.pdf">Annual Report 2025</a></main>',
 'https://acme.example/events':'<main><h1>Events</h1><a href="/investor-day">Investor Day March 15, 2025</a><a href="/earnings-transcript">Earnings transcript May 1, 2025</a></main>',
 'https://acme.example/investor-day':'<main><h1>Investor day</h1><p>Our strategic priority is cloud efficiency.</p></main>',
 'https://acme.example/earnings-transcript':'<main><h1>Earnings call</h1><p>Acme announced a new AI platform initiative.</p></main>',
 'https://acme.example/leadership':leadership,
 'https://acme.example/leadership/jane':'<main><h1>Jane Smith</h1><p>Jane Smith is our Chief Technology Officer overseeing cloud investments.</p></main>'
 };return async url=>{if(url.includes('sec.gov/Archives'))return {url,body:'<main>Our strategic priority is cloud growth. We announced a new AI platform.</main>',format:'html'};if(url.endsWith('report.pdf'))return {url,body:'Our annual report sets out a strategic cloud investment priority.',format:'pdf',pages:2};if(!pages[url])throw new Error('Fixture page unavailable: '+url);return {url,body:pages[url],format:'html'};};}
test('collector crawls archive pages and reviews linked investor-day, transcript and PDF alongside multiple SEC filings',async()=>{const b=await collectResearch({company:'ACME',investorUrl:'https://acme.example/ir',websiteUrl:'https://acme.example',leadershipUrl:'https://acme.example/leadership',months:24,maxDocuments:12},buildBrief,{now:Date.parse('2025-06-01'),fetcher:fixture(),jsonFetcher:async url=>url.includes('tickers')?tickers:issuer});assert.equal(b.sources.filter(s=>s.provenance==='Retrieved SEC filing').length,2);assert.ok(b.sources.some(s=>s.type==='Investor day'));assert.ok(b.sources.some(s=>s.type==='Earnings transcript'));assert.ok(b.sources.some(s=>s.format==='pdf'));assert.equal(b.leaders.length,2);assert.equal(b.leaders[0].reportsTo,null);assert.ok(b.catalog.some(c=>c.url.endsWith('annual-reports')&&c.type==='Investor center'));assert.ok(b.orgChart.nodes.every(n=>!n.reportsTo));});
test('collector discloses document limits and fetch failures without losing successful research',async()=>{const b=await collectResearch({company:'ACME',investorUrl:'https://acme.example/ir',websiteUrl:'https://acme.example',leadershipUrl:'https://acme.example/blocked',maxDocuments:4},buildBrief,{now:Date.parse('2025-06-01'),fetcher:fixture(),jsonFetcher:async url=>url.includes('tickers')?tickers:issuer});assert.ok(b.sources.length>0);assert.ok(b.catalog.some(c=>c.status==='Not reviewed'));assert.ok(b.failures.some(f=>f.source==='Company leadership'));assert.ok(b.scope.notReviewed>0);});
test('job queue runs concurrently, isolates failures and deduplicates accounts',async()=>{let active=0,max=0;const queue=new JobQueue(async input=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,20));active--;if(input.company==='Broken')throw new Error('Unavailable');return {sources:[{id:'S1'}],failures:[]};});const start=queue.create(['Acme','Acme','Beta','Broken']);assert.equal(start.total,3);await new Promise(r=>setTimeout(r,100));const end=queue.snapshot(start.id);assert.equal(end.status,'finished');assert.equal(end.completed,3);assert.equal(max,2);assert.equal(end.items[2].status,'failed');assert.equal(end.items[2].error,'Unavailable');});
test('cancel skips queued accounts while retaining an in-flight result',async()=>{let release;const queue=new JobQueue(()=>new Promise(r=>{release=r;}),{concurrency:1});const start=queue.create(['Acme','Beta']);await new Promise(r=>setTimeout(r,0));queue.cancel(start.id);assert.equal(queue.snapshot(start.id).items[1].status,'cancelled');release({sources:[{}],failures:[]});await new Promise(r=>setTimeout(r,0));assert.equal(queue.snapshot(start.id).status,'cancelled');assert.equal(queue.snapshot(start.id).items[0].status,'complete');});
test('span-based leadership cards seed people and distinguish board outside roles',()=>{const html='<h2>Executive Biographies</h2><a href="/person"><span><span>Jane Smith</span><p>Chief Technology Officer</p></span></a><h2>Board of Directors</h2><article><h3>David Jones</h3><p>Former CEO of Another Company</p></article>';const p=extractLeaders(html,'https://acme.example/leadership','S1',null);assert.equal(p.length,2);assert.equal(p[0].name,'Jane Smith');assert.equal(p[1].membership,'Board');assert.match(p[1].status,/external/);});
test('Q4 public feed supplies dated document links and filters older reports',async()=>{const {q4Documents}=await import('../investor-feeds.js');const docs=q4Documents({GetFinancialReportListResult:[{ReportTitle:'Q1 2025',ReportDate:'2025-05-01T00:00:00',ReportYear:2025,Documents:[{DocumentTitle:'10-Q',DocumentCategory:'tenq',DocumentPath:'https://acme.example/q.pdf'},{DocumentTitle:'Press Release',DocumentPath:'https://acme.example/release'}]},{ReportTitle:'Old report',ReportDate:'2020-01-01',Documents:[{DocumentTitle:'Annual Report',DocumentPath:'https://acme.example/old.pdf'}]}]},'https://acme.example/ir','2024-01-01');assert.equal(docs.length,2);assert.equal(docs[0].type,'10-Q');assert.equal(docs[0].date,'2025-05-01');assert.equal(docs[1].type,'Earnings results');assert.equal(docs[0].dateKind,'Investor-center report date');});
