import test from 'node:test';import assert from 'node:assert/strict';import {buildBrief,research,safeURL,plainText} from '../research.js';
const passage='Acme appointed Jane Smith as chief technology officer. Our strategic priority is operational efficiency. We use Azure cloud infrastructure for our applications. Acme announced a customer service transformation initiative.';
test('imported evidence supports traceable hypotheses without invented leaders',async()=>{const b=await research({company:'Acme',live:false,materials:[{title:'Annual report',type:'10-K',date:'2025-02-20',url:'https://example.com/report',text:passage}]});assert.equal(b.sources.length,1);assert.equal(b.facts.leaders.length,1);assert.equal(b.facts.leaders[0].quote,'Acme appointed Jane Smith as chief technology officer.');assert.equal(b.facts.leaders[0].sourceId,'S1');assert.equal(b.facts.leaders[0].date,'2025-02-20');assert.ok(b.hypotheses.length>0);const ids=new Set(Object.values(b.facts).flat().map(f=>f.id));for(const h of b.hypotheses)for(const id of h.evidence)assert.ok(ids.has(id));assert.ok(b.gaps.some(g=>g.includes('10-Q')));});
test('empty research returns gaps and no hypotheses',()=>{const b=buildBrief('Acme',[],[{source:'SEC',message:'Unavailable'}]);assert.equal(b.hypotheses.length,0);assert.equal(b.facts.leaders.length,0);assert.equal(b.failures.length,1);assert.ok(b.gaps.includes('No 10-K was successfully reviewed.'));});
test('untrusted URLs cannot target local services or embed credentials',()=>{for(const u of ['http://example.com','https://localhost','https://127.0.0.1','https://[::1]','https://user:password@example.com','https://example.com:8443','https://service.internal'])assert.throws(()=>safeURL(u));assert.equal(safeURL('https://example.com/report').hostname,'example.com');});
test('HTML extraction removes executable text and decodes entities',()=>assert.equal(plainText('<script>evil()</script><p>Cloud &amp; AI</p>'),'Cloud & AI'));
test('invalid company is rejected',async()=>assert.rejects(()=>research({company:'',live:false}),/company name/));
test('unknown dates stay unknown and imported sources remain identified',async()=>{const b=await research({company:'Acme',live:false,materials:[{text:passage}]});assert.equal(b.sources[0].date,null);assert.match(b.sources[0].provenance,/User-provided/);assert.ok(b.gaps.some(x=>x.includes('publication date')));});
test('executive initials remain intact and technology leaders outrank generic executives',()=>{const b=buildBrief('Acme',[{id:'S1',title:'Report',type:'10-K',text:'Amy E. Hood is chief financial officer. Kevin Scott is chief technology officer. Jane Doe is chief information security officer.'}]);assert.ok(b.facts.leaders.some(f=>f.quote==='Amy E. Hood is chief financial officer.'));assert.equal(b.facts.leaders[0].quote,'Kevin Scott is chief technology officer.');assert.ok(!b.gaps.some(g=>g.startsWith('CISO role')));});

test('filing typography entities are decoded',()=>assert.equal(plainText('Our &#8220;CISO&#8221; and Board&#8217;s strategy.'),'Our “CISO” and Board’s strategy.'));
